// flow-typed signature: 56cb950bb5f0823df02c722af5770633
// flow-typed version: <<STUB>>/ansi-to-react_v0.0.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-to-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-to-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ansi-to-react/lib/anser' {
  declare module.exports: any;
}

declare module 'ansi-to-react/lib/index' {
  declare module.exports: any;
}

declare module 'ansi-to-react/src/anser' {
  declare module.exports: any;
}

declare module 'ansi-to-react/src/index' {
  declare module.exports: any;
}

declare module 'ansi-to-react/test/anser-spec' {
  declare module.exports: any;
}

declare module 'ansi-to-react/test/index-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ansi-to-react/lib/anser.js' {
  declare module.exports: $Exports<'ansi-to-react/lib/anser'>;
}
declare module 'ansi-to-react/lib/index.js' {
  declare module.exports: $Exports<'ansi-to-react/lib/index'>;
}
declare module 'ansi-to-react/src/anser.js' {
  declare module.exports: $Exports<'ansi-to-react/src/anser'>;
}
declare module 'ansi-to-react/src/index.js' {
  declare module.exports: $Exports<'ansi-to-react/src/index'>;
}
declare module 'ansi-to-react/test/anser-spec.js' {
  declare module.exports: $Exports<'ansi-to-react/test/anser-spec'>;
}
declare module 'ansi-to-react/test/index-spec.js' {
  declare module.exports: $Exports<'ansi-to-react/test/index-spec'>;
}
