// flow-typed signature: c13c6b776bef174b5366ebe803a01f64
// flow-typed version: <<STUB>>/commonmark-react-renderer_v^4.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commonmark-react-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'commonmark-react-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'commonmark-react-renderer/examples/usage' {
  declare module.exports: any;
}

declare module 'commonmark-react-renderer/src/commonmark-react-renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'commonmark-react-renderer/examples/usage.js' {
  declare module.exports: $Exports<'commonmark-react-renderer/examples/usage'>;
}
declare module 'commonmark-react-renderer/src/commonmark-react-renderer.js' {
  declare module.exports: $Exports<'commonmark-react-renderer/src/commonmark-react-renderer'>;
}
