// flow-typed signature: 50b0270337806c9cdb66fbd915d1cbbc
// flow-typed version: <<STUB>>/electron-react-devtools_v^0.4.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-react-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-react-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-react-devtools/api' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/backend' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/background' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/contentScript' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/inject' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/main' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/panel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-react-devtools/api.js' {
  declare module.exports: $Exports<'electron-react-devtools/api'>;
}
declare module 'electron-react-devtools/build/backend.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/backend'>;
}
declare module 'electron-react-devtools/build/background.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/background'>;
}
declare module 'electron-react-devtools/build/contentScript.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/contentScript'>;
}
declare module 'electron-react-devtools/build/inject.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/inject'>;
}
declare module 'electron-react-devtools/build/main.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/main'>;
}
declare module 'electron-react-devtools/build/panel.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/panel'>;
}
