// flow-typed signature: b85ddd6dc1dabb2cba8a5de48b52a5d9
// flow-typed version: <<STUB>>/electron-mocha_v^3.0.6/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-mocha/args' {
  declare module.exports: any;
}

declare module 'electron-mocha/mocha' {
  declare module.exports: any;
}

declare module 'electron-mocha/renderer/console' {
  declare module.exports: any;
}

declare module 'electron-mocha/renderer/index' {
  declare module.exports: any;
}

declare module 'electron-mocha/renderer/run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-mocha/args.js' {
  declare module.exports: $Exports<'electron-mocha/args'>;
}
declare module 'electron-mocha/index' {
  declare module.exports: $Exports<'electron-mocha'>;
}
declare module 'electron-mocha/index.js' {
  declare module.exports: $Exports<'electron-mocha'>;
}
declare module 'electron-mocha/mocha.js' {
  declare module.exports: $Exports<'electron-mocha/mocha'>;
}
declare module 'electron-mocha/renderer/console.js' {
  declare module.exports: $Exports<'electron-mocha/renderer/console'>;
}
declare module 'electron-mocha/renderer/index.js' {
  declare module.exports: $Exports<'electron-mocha/renderer/index'>;
}
declare module 'electron-mocha/renderer/run.js' {
  declare module.exports: $Exports<'electron-mocha/renderer/run'>;
}
