// flow-typed signature: 0a92f119c7464148cef00d2c1bc67c1f
// flow-typed version: <<STUB>>/electron-osx-sign_v^0.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-osx-sign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-osx-sign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-osx-sign/bin/electron-osx-flat' {
  declare module.exports: any;
}

declare module 'electron-osx-sign/bin/electron-osx-sign' {
  declare module.exports: any;
}

declare module 'electron-osx-sign/test/basic' {
  declare module.exports: any;
}

declare module 'electron-osx-sign/test/index' {
  declare module.exports: any;
}

declare module 'electron-osx-sign/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-osx-sign/bin/electron-osx-flat.js' {
  declare module.exports: $Exports<'electron-osx-sign/bin/electron-osx-flat'>;
}
declare module 'electron-osx-sign/bin/electron-osx-sign.js' {
  declare module.exports: $Exports<'electron-osx-sign/bin/electron-osx-sign'>;
}
declare module 'electron-osx-sign/index' {
  declare module.exports: $Exports<'electron-osx-sign'>;
}
declare module 'electron-osx-sign/index.js' {
  declare module.exports: $Exports<'electron-osx-sign'>;
}
declare module 'electron-osx-sign/test/basic.js' {
  declare module.exports: $Exports<'electron-osx-sign/test/basic'>;
}
declare module 'electron-osx-sign/test/index.js' {
  declare module.exports: $Exports<'electron-osx-sign/test/index'>;
}
declare module 'electron-osx-sign/test/util.js' {
  declare module.exports: $Exports<'electron-osx-sign/test/util'>;
}
