// flow-typed signature: e548ca1e802121e1bb33980b66709efe
// flow-typed version: <<STUB>>/enchannel-zmq-backend_v^2.5.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enchannel-zmq-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'enchannel-zmq-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enchannel-zmq-backend/lib/constants' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/lib/index' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/lib/subjection' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/scripts/repl' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/src/constants' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/src/index' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/src/subjection' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/test/channeling_spec' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/test/constants_spec' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/test/index_spec' {
  declare module.exports: any;
}

declare module 'enchannel-zmq-backend/test/subjection_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enchannel-zmq-backend/lib/constants.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/lib/constants'>;
}
declare module 'enchannel-zmq-backend/lib/index.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/lib/index'>;
}
declare module 'enchannel-zmq-backend/lib/subjection.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/lib/subjection'>;
}
declare module 'enchannel-zmq-backend/scripts/repl.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/scripts/repl'>;
}
declare module 'enchannel-zmq-backend/src/constants.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/src/constants'>;
}
declare module 'enchannel-zmq-backend/src/index.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/src/index'>;
}
declare module 'enchannel-zmq-backend/src/subjection.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/src/subjection'>;
}
declare module 'enchannel-zmq-backend/test/channeling_spec.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/test/channeling_spec'>;
}
declare module 'enchannel-zmq-backend/test/constants_spec.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/test/constants_spec'>;
}
declare module 'enchannel-zmq-backend/test/index_spec.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/test/index_spec'>;
}
declare module 'enchannel-zmq-backend/test/subjection_spec.js' {
  declare module.exports: $Exports<'enchannel-zmq-backend/test/subjection_spec'>;
}
