// flow-typed signature: c9b932facc17a78f6ec292c232cc23b8
// flow-typed version: <<STUB>>/github_v^5.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'github' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github/doc/apidoc' {
  declare module.exports: any;
}

declare module 'github/examples/addCollaborator' {
  declare module.exports: any;
}

declare module 'github/examples/addLabelsToIssue' {
  declare module.exports: any;
}

declare module 'github/examples/createFile' {
  declare module.exports: any;
}

declare module 'github/examples/getContent' {
  declare module.exports: any;
}

declare module 'github/examples/getFollowers' {
  declare module.exports: any;
}

declare module 'github/examples/getFollowing' {
  declare module.exports: any;
}

declare module 'github/examples/getIssuesForRepo' {
  declare module.exports: any;
}

declare module 'github/examples/getNextPage' {
  declare module.exports: any;
}

declare module 'github/examples/getOrgPublicMembers' {
  declare module.exports: any;
}

declare module 'github/examples/getRawBlob' {
  declare module.exports: any;
}

declare module 'github/examples/getReactionsForIssue' {
  declare module.exports: any;
}

declare module 'github/examples/getReleaseAsset' {
  declare module.exports: any;
}

declare module 'github/examples/getRepos' {
  declare module.exports: any;
}

declare module 'github/examples/getStarred' {
  declare module.exports: any;
}

declare module 'github/examples/getUser' {
  declare module.exports: any;
}

declare module 'github/examples/getUserById' {
  declare module.exports: any;
}

declare module 'github/examples/getUserOrgs' {
  declare module.exports: any;
}

declare module 'github/examples/listOrgs' {
  declare module.exports: any;
}

declare module 'github/examples/lockIssue' {
  declare module.exports: any;
}

declare module 'github/examples/paginationCustomHeaders' {
  declare module.exports: any;
}

declare module 'github/examples/removeAssigneesFromIssue' {
  declare module.exports: any;
}

declare module 'github/examples/renderMarkdown' {
  declare module.exports: any;
}

declare module 'github/examples/searchIssues' {
  declare module.exports: any;
}

declare module 'github/examples/searchMostStarredRepos' {
  declare module.exports: any;
}

declare module 'github/examples/testPromise' {
  declare module.exports: any;
}

declare module 'github/examples/testPromiseGetNextPage' {
  declare module.exports: any;
}

declare module 'github/examples/testPromiseQ' {
  declare module.exports: any;
}

declare module 'github/examples/updateBranchProtection' {
  declare module.exports: any;
}

declare module 'github/examples/updateLabel' {
  declare module.exports: any;
}

declare module 'github/lib/error' {
  declare module.exports: any;
}

declare module 'github/lib/generate' {
  declare module.exports: any;
}

declare module 'github/lib/index' {
  declare module.exports: any;
}

declare module 'github/lib/promise' {
  declare module.exports: any;
}

declare module 'github/lib/util' {
  declare module.exports: any;
}

declare module 'github/test/activityTest' {
  declare module.exports: any;
}

declare module 'github/test/authorizationTest' {
  declare module.exports: any;
}

declare module 'github/test/enterpriseTest' {
  declare module.exports: any;
}

declare module 'github/test/gistsTest' {
  declare module.exports: any;
}

declare module 'github/test/gitdataTest' {
  declare module.exports: any;
}

declare module 'github/test/installationsTest' {
  declare module.exports: any;
}

declare module 'github/test/integrationsTest' {
  declare module.exports: any;
}

declare module 'github/test/issuesTest' {
  declare module.exports: any;
}

declare module 'github/test/migrationsTest' {
  declare module.exports: any;
}

declare module 'github/test/miscTest' {
  declare module.exports: any;
}

declare module 'github/test/orgsTest' {
  declare module.exports: any;
}

declare module 'github/test/pullRequestsTest' {
  declare module.exports: any;
}

declare module 'github/test/reactionsTest' {
  declare module.exports: any;
}

declare module 'github/test/reposTest' {
  declare module.exports: any;
}

declare module 'github/test/searchTest' {
  declare module.exports: any;
}

declare module 'github/test/usersTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github/doc/apidoc.js' {
  declare module.exports: $Exports<'github/doc/apidoc'>;
}
declare module 'github/examples/addCollaborator.js' {
  declare module.exports: $Exports<'github/examples/addCollaborator'>;
}
declare module 'github/examples/addLabelsToIssue.js' {
  declare module.exports: $Exports<'github/examples/addLabelsToIssue'>;
}
declare module 'github/examples/createFile.js' {
  declare module.exports: $Exports<'github/examples/createFile'>;
}
declare module 'github/examples/getContent.js' {
  declare module.exports: $Exports<'github/examples/getContent'>;
}
declare module 'github/examples/getFollowers.js' {
  declare module.exports: $Exports<'github/examples/getFollowers'>;
}
declare module 'github/examples/getFollowing.js' {
  declare module.exports: $Exports<'github/examples/getFollowing'>;
}
declare module 'github/examples/getIssuesForRepo.js' {
  declare module.exports: $Exports<'github/examples/getIssuesForRepo'>;
}
declare module 'github/examples/getNextPage.js' {
  declare module.exports: $Exports<'github/examples/getNextPage'>;
}
declare module 'github/examples/getOrgPublicMembers.js' {
  declare module.exports: $Exports<'github/examples/getOrgPublicMembers'>;
}
declare module 'github/examples/getRawBlob.js' {
  declare module.exports: $Exports<'github/examples/getRawBlob'>;
}
declare module 'github/examples/getReactionsForIssue.js' {
  declare module.exports: $Exports<'github/examples/getReactionsForIssue'>;
}
declare module 'github/examples/getReleaseAsset.js' {
  declare module.exports: $Exports<'github/examples/getReleaseAsset'>;
}
declare module 'github/examples/getRepos.js' {
  declare module.exports: $Exports<'github/examples/getRepos'>;
}
declare module 'github/examples/getStarred.js' {
  declare module.exports: $Exports<'github/examples/getStarred'>;
}
declare module 'github/examples/getUser.js' {
  declare module.exports: $Exports<'github/examples/getUser'>;
}
declare module 'github/examples/getUserById.js' {
  declare module.exports: $Exports<'github/examples/getUserById'>;
}
declare module 'github/examples/getUserOrgs.js' {
  declare module.exports: $Exports<'github/examples/getUserOrgs'>;
}
declare module 'github/examples/listOrgs.js' {
  declare module.exports: $Exports<'github/examples/listOrgs'>;
}
declare module 'github/examples/lockIssue.js' {
  declare module.exports: $Exports<'github/examples/lockIssue'>;
}
declare module 'github/examples/paginationCustomHeaders.js' {
  declare module.exports: $Exports<'github/examples/paginationCustomHeaders'>;
}
declare module 'github/examples/removeAssigneesFromIssue.js' {
  declare module.exports: $Exports<'github/examples/removeAssigneesFromIssue'>;
}
declare module 'github/examples/renderMarkdown.js' {
  declare module.exports: $Exports<'github/examples/renderMarkdown'>;
}
declare module 'github/examples/searchIssues.js' {
  declare module.exports: $Exports<'github/examples/searchIssues'>;
}
declare module 'github/examples/searchMostStarredRepos.js' {
  declare module.exports: $Exports<'github/examples/searchMostStarredRepos'>;
}
declare module 'github/examples/testPromise.js' {
  declare module.exports: $Exports<'github/examples/testPromise'>;
}
declare module 'github/examples/testPromiseGetNextPage.js' {
  declare module.exports: $Exports<'github/examples/testPromiseGetNextPage'>;
}
declare module 'github/examples/testPromiseQ.js' {
  declare module.exports: $Exports<'github/examples/testPromiseQ'>;
}
declare module 'github/examples/updateBranchProtection.js' {
  declare module.exports: $Exports<'github/examples/updateBranchProtection'>;
}
declare module 'github/examples/updateLabel.js' {
  declare module.exports: $Exports<'github/examples/updateLabel'>;
}
declare module 'github/lib/error.js' {
  declare module.exports: $Exports<'github/lib/error'>;
}
declare module 'github/lib/generate.js' {
  declare module.exports: $Exports<'github/lib/generate'>;
}
declare module 'github/lib/index.js' {
  declare module.exports: $Exports<'github/lib/index'>;
}
declare module 'github/lib/promise.js' {
  declare module.exports: $Exports<'github/lib/promise'>;
}
declare module 'github/lib/util.js' {
  declare module.exports: $Exports<'github/lib/util'>;
}
declare module 'github/test/activityTest.js' {
  declare module.exports: $Exports<'github/test/activityTest'>;
}
declare module 'github/test/authorizationTest.js' {
  declare module.exports: $Exports<'github/test/authorizationTest'>;
}
declare module 'github/test/enterpriseTest.js' {
  declare module.exports: $Exports<'github/test/enterpriseTest'>;
}
declare module 'github/test/gistsTest.js' {
  declare module.exports: $Exports<'github/test/gistsTest'>;
}
declare module 'github/test/gitdataTest.js' {
  declare module.exports: $Exports<'github/test/gitdataTest'>;
}
declare module 'github/test/installationsTest.js' {
  declare module.exports: $Exports<'github/test/installationsTest'>;
}
declare module 'github/test/integrationsTest.js' {
  declare module.exports: $Exports<'github/test/integrationsTest'>;
}
declare module 'github/test/issuesTest.js' {
  declare module.exports: $Exports<'github/test/issuesTest'>;
}
declare module 'github/test/migrationsTest.js' {
  declare module.exports: $Exports<'github/test/migrationsTest'>;
}
declare module 'github/test/miscTest.js' {
  declare module.exports: $Exports<'github/test/miscTest'>;
}
declare module 'github/test/orgsTest.js' {
  declare module.exports: $Exports<'github/test/orgsTest'>;
}
declare module 'github/test/pullRequestsTest.js' {
  declare module.exports: $Exports<'github/test/pullRequestsTest'>;
}
declare module 'github/test/reactionsTest.js' {
  declare module.exports: $Exports<'github/test/reactionsTest'>;
}
declare module 'github/test/reposTest.js' {
  declare module.exports: $Exports<'github/test/reposTest'>;
}
declare module 'github/test/searchTest.js' {
  declare module.exports: $Exports<'github/test/searchTest'>;
}
declare module 'github/test/usersTest.js' {
  declare module.exports: $Exports<'github/test/usersTest'>;
}
