// flow-typed signature: feb7415082ba3d8be0b6c8ffe60bdc3a
// flow-typed version: <<STUB>>/jsx-chai_v^4.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsx-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsx-chai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsx-chai/dist/jsx-chai.min' {
  declare module.exports: any;
}

declare module 'jsx-chai/gulpfile' {
  declare module.exports: any;
}

declare module 'jsx-chai/lib/jsx-chai' {
  declare module.exports: any;
}

declare module 'jsx-chai/src/jsx-chai' {
  declare module.exports: any;
}

declare module 'jsx-chai/test/test-jsx-chai' {
  declare module.exports: any;
}

declare module 'jsx-chai/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsx-chai/dist/jsx-chai.min.js' {
  declare module.exports: $Exports<'jsx-chai/dist/jsx-chai.min'>;
}
declare module 'jsx-chai/gulpfile.js' {
  declare module.exports: $Exports<'jsx-chai/gulpfile'>;
}
declare module 'jsx-chai/lib/jsx-chai.js' {
  declare module.exports: $Exports<'jsx-chai/lib/jsx-chai'>;
}
declare module 'jsx-chai/src/jsx-chai.js' {
  declare module.exports: $Exports<'jsx-chai/src/jsx-chai'>;
}
declare module 'jsx-chai/test/test-jsx-chai.js' {
  declare module.exports: $Exports<'jsx-chai/test/test-jsx-chai'>;
}
declare module 'jsx-chai/webpack.config.js' {
  declare module.exports: $Exports<'jsx-chai/webpack.config'>;
}
