// flow-typed signature: fc9bf8bec4792a534d56be97f566d21f
// flow-typed version: <<STUB>>/jupyter-paths_v^1.0.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jupyter-paths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jupyter-paths' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jupyter-paths/test/jupyter_paths_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jupyter-paths/index' {
  declare module.exports: $Exports<'jupyter-paths'>;
}
declare module 'jupyter-paths/index.js' {
  declare module.exports: $Exports<'jupyter-paths'>;
}
declare module 'jupyter-paths/test/jupyter_paths_spec.js' {
  declare module.exports: $Exports<'jupyter-paths/test/jupyter_paths_spec'>;
}
