// flow-typed signature: 64b4d3a9e42493922dca452d41285e0e
// flow-typed version: <<STUB>>/mathjax-electron_v^1.1.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mathjax-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mathjax-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mathjax-electron/dist/index' {
  declare module.exports: any;
}

declare module 'mathjax-electron/lib/mathjax-electron' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/MathEvents' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/AMSmath' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/AMSsymbols' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/bbox' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/boldsymbol' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/HTML' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/mathchoice' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/newcommand' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/noErrors' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/noUndefined' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/unicode' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/TeX/verb' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/extensions/tex2jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/Arrows' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/BasicLatin' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/CombDiacritMarks' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/CombDiactForSymbols' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/Dingbats' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/GeneralPunctuation' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/GeometricShapes' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/GreekAndCoptic' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/Latin1Supplement' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/LetterlikeSymbols' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MathOperators' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscMathSymbolsA' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscMathSymbolsB' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscSymbolsAndArrows' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscTechnical' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SpacingModLetters' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SupplementalArrowsA' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SupplementalArrowsB' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SuppMathOperators' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/input/TeX/config' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/input/TeX/jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/annotation-xml' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/maction' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/menclose' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mglyph' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mmultiscripts' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/ms' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mtable' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/multiline' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/config' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Arrows/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Arrows/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/fontdata-extra' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/fontdata' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Fraktur/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Fraktur/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Monospace/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Operators/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Operators/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size1/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size2/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size3/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size4/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size5/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Symbols/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Symbols/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Bold/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/BoldItalic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Italic/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Regular/Main' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/jax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/resources/MathJax/MathJax' {
  declare module.exports: any;
}

declare module 'mathjax-electron/src/mathjax-electron' {
  declare module.exports: any;
}

declare module 'mathjax-electron/test/mathjax-electron.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mathjax-electron/dist/index.js' {
  declare module.exports: $Exports<'mathjax-electron/dist/index'>;
}
declare module 'mathjax-electron/lib/mathjax-electron.js' {
  declare module.exports: $Exports<'mathjax-electron/lib/mathjax-electron'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/MathEvents.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/MathEvents'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/AMSmath.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/AMSmath'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/AMSsymbols.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/AMSsymbols'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/bbox.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/bbox'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/boldsymbol.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/boldsymbol'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/HTML.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/HTML'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/mathchoice.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/mathchoice'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/newcommand.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/newcommand'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/noErrors.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/noErrors'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/noUndefined.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/noUndefined'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/unicode.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/unicode'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/TeX/verb.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/TeX/verb'>;
}
declare module 'mathjax-electron/resources/MathJax/extensions/tex2jax.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/extensions/tex2jax'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/jax.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/jax'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/Arrows.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/Arrows'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/BasicLatin.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/BasicLatin'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/CombDiacritMarks.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/CombDiacritMarks'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/CombDiactForSymbols.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/CombDiactForSymbols'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/Dingbats.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/Dingbats'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/GeneralPunctuation.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/GeneralPunctuation'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/GeometricShapes.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/GeometricShapes'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/GreekAndCoptic.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/GreekAndCoptic'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/Latin1Supplement.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/Latin1Supplement'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/LetterlikeSymbols.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/LetterlikeSymbols'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MathOperators.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/MathOperators'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscMathSymbolsA.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscMathSymbolsA'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscMathSymbolsB.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscMathSymbolsB'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscSymbolsAndArrows.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscSymbolsAndArrows'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscTechnical.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/MiscTechnical'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SpacingModLetters.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/SpacingModLetters'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SupplementalArrowsA.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/SupplementalArrowsA'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SupplementalArrowsB.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/SupplementalArrowsB'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/element/mml/optable/SuppMathOperators.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/element/mml/optable/SuppMathOperators'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/input/TeX/config.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/input/TeX/config'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/input/TeX/jax.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/input/TeX/jax'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/annotation-xml.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/annotation-xml'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/maction.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/maction'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/menclose.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/menclose'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mglyph.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mglyph'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mmultiscripts.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mmultiscripts'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/ms.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/ms'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mtable.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/mtable'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/multiline.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/autoload/multiline'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/config.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/config'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Alphabets/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Arrows/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Arrows/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Arrows/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Arrows/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/DoubleStruck/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/fontdata-extra.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/fontdata-extra'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/fontdata.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/fontdata'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Fraktur/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Fraktur/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Fraktur/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Fraktur/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Latin/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Main/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Marks/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Misc/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Monospace/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Monospace/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Normal/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Operators/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Operators/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Operators/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Operators/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/SansSerif/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Script/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Shapes/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size1/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size1/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size2/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size2/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size3/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size3/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size4/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size4/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size5/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Size5/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Symbols/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Symbols/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Symbols/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Symbols/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Bold/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Bold/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/BoldItalic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/BoldItalic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Italic/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Italic/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Regular/Main.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/fonts/STIX-Web/Variants/Regular/Main'>;
}
declare module 'mathjax-electron/resources/MathJax/jax/output/SVG/jax.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/jax/output/SVG/jax'>;
}
declare module 'mathjax-electron/resources/MathJax/MathJax.js' {
  declare module.exports: $Exports<'mathjax-electron/resources/MathJax/MathJax'>;
}
declare module 'mathjax-electron/src/mathjax-electron.js' {
  declare module.exports: $Exports<'mathjax-electron/src/mathjax-electron'>;
}
declare module 'mathjax-electron/test/mathjax-electron.test.js' {
  declare module.exports: $Exports<'mathjax-electron/test/mathjax-electron.test'>;
}
