// flow-typed signature: 6f1156abfc7595a95288412f6ed4d82b
// flow-typed version: <<STUB>>/plotly.js_v^1.17.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plotly.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'plotly.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plotly.js/build/plotcss' {
  declare module.exports: any;
}

declare module 'plotly.js/build/ploticon' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-basic' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-basic.min' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-cartesian' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-cartesian.min' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-geo-assets' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-geo' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-geo.min' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-gl2d' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-gl2d.min' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-gl3d' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-gl3d.min' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-mapbox' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-mapbox.min' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly-with-meta' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly' {
  declare module.exports: any;
}

declare module 'plotly.js/dist/plotly.min' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/bar' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/box' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/choropleth' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/contour' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/contourgl' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/core' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/heatmap' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/heatmapgl' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/histogram' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/histogram2d' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/histogram2dcontour' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/index-basic' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/index-cartesian' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/index-geo' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/index-gl2d' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/index-gl3d' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/index-mapbox' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/index' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/mesh3d' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/pie' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/pointcloud' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/scatter' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/scatter3d' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/scattergeo' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/scattergl' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/scattermapbox' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/scatterternary' {
  declare module.exports: any;
}

declare module 'plotly.js/lib/surface' {
  declare module.exports: any;
}

declare module 'plotly.js/src/assets/geo_assets' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/annotation_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/arrow_paths' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/calc_autorange' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/draw_arrow_head' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/draw' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/annotations/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/color/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/color/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorbar/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorbar/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorbar/draw' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorbar/has_colorbar' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorbar/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/color_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/default_scale' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/flip_scale' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/get_scale' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/has_colorscale' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/is_valid_scale_array' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/is_valid_scale' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/make_scale_function' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/colorscale/scales' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/dragelement/align' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/dragelement/cursor' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/dragelement/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/dragelement/unhover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/drawing/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/drawing/symbol_defs' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/errorbars/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/errorbars/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/errorbars/compute_error' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/errorbars/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/errorbars/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/errorbars/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/errorbars/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/images/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/images/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/images/draw' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/images/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/anchor_utils' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/draw' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/get_legend_data' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/helpers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/legend/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/modebar/buttons' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/modebar/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/modebar/manage' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/modebar/modebar' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeselector/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeselector/button_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeselector/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeselector/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeselector/draw' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeselector/get_update_object' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeselector/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeslider/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeslider/create_slider' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeslider/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeslider/helpers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeslider/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/rangeslider/range_plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/calc_autorange' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/draw' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/helpers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/shapes/shape_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/titles/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/updatemenus/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/updatemenus/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/updatemenus/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/updatemenus/draw' {
  declare module.exports: any;
}

declare module 'plotly.js/src/components/updatemenus/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/constants/gl_markers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/constants/gl2d_dashes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/constants/gl3d_dashes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/constants/string_mappings' {
  declare module.exports: any;
}

declare module 'plotly.js/src/constants/xmlns_namespaces' {
  declare module.exports: any;
}

declare module 'plotly.js/src/core' {
  declare module.exports: any;
}

declare module 'plotly.js/src/fonts/mathjax_config' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/array_to_calc_item' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/coerce' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/dates' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/events' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/extend' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/filter_visible' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/float32_truncate' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/geo_location_utils' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/gl_format_color' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/html2unicode' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/is_array' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/is_plain_object' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/loggers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/matrix' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/nested_property' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/notifier' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/polygon' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/queue' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/search' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/setcursor' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/show_no_webgl_msg' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/stats' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/str2rgbarray' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/svg_text_utils' {
  declare module.exports: any;
}

declare module 'plotly.js/src/lib/topojson_utils' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/helpers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/plot_api' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/plot_config' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/plot_schema' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/register' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/set_plot_config' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/subroutines' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/to_image' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plot_api/validate' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plotly' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/animation_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/axes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/axis_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/axis_ids' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/category_order_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/clean_datum' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/dragbox' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/graph_interact' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/layout_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/ordered_categories' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/position_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/select' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/set_convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/tick_label_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/tick_mark_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/tick_value_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/cartesian/transition_axes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/font_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/frame_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/geo' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/layout/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/layout/axis_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/layout/axis_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/layout/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/layout/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/projections' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/set_scale' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/zoom_reset' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/geo/zoom' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl2d/camera' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl2d/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl2d/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl2d/scene2d' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/camera' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/axis_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/axis_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/spikes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/layout/tick_marks' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/project' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/scene' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/gl3d/set_convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/mapbox/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/mapbox/convert_text_opts' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/mapbox/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/mapbox/layers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/mapbox/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/mapbox/layout_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/mapbox/mapbox' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/plots' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/polar/area_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/polar/axis_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/polar/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/polar/micropolar_manager' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/polar/micropolar' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/polar/undo_manager' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/subplot_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/ternary/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/ternary/layout/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/ternary/layout/axis_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/ternary/layout/axis_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/ternary/layout/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/ternary/layout/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/plots/ternary/ternary' {
  declare module.exports: any;
}

declare module 'plotly.js/src/registry' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/cloneplot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/download' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/filesaver' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/helpers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/svgtoimg' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/toimage' {
  declare module.exports: any;
}

declare module 'plotly.js/src/snapshot/tosvg' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/arrays_to_calcdata' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/hover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/layout_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/set_positions' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/style_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/bar/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/hover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/layout_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/set_positions' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/box/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/choropleth/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/choropleth/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/choropleth/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/choropleth/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/choropleth/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/colorbar' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/hover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/make_color_map' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/style_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contour/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contourgl/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/contourgl/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/colorbar' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/convert_column_xyz' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/has_columns' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/hover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/max_row_length' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmap/xyz_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmapgl/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmapgl/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/heatmapgl/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/average' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/bin_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/bin_functions' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram/norm_functions' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2d/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2d/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2d/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2d/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2d/sample_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2dcontour/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2dcontour/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/histogram2dcontour/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/mesh3d/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/mesh3d/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/mesh3d/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/mesh3d/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/base_plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/helpers' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/layout_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/layout_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/style_one' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pie/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pointcloud/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pointcloud/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pointcloud/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/pointcloud/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/arrays_to_calcdata' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/clean_data' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/colorbar' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/colorscale_calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/fillcolor_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/get_trace_color' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/hover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/line_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/line_points' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/line_shape_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/link_traces' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/make_bubble_size_func' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/marker_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/select' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/subtypes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/text_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter/xy_defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter3d/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter3d/calc_errors' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter3d/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter3d/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter3d/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatter3d/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergeo/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergeo/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergeo/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergeo/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergeo/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergl/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergl/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergl/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattergl/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattermapbox/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattermapbox/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattermapbox/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattermapbox/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattermapbox/hover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattermapbox/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scattermapbox/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/hover' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/index' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/plot' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/select' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/scatterternary/style' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/surface/attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/surface/calc' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/surface/colorbar' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/surface/convert' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/surface/defaults' {
  declare module.exports: any;
}

declare module 'plotly.js/src/traces/surface/index' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/baseline' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/bundle' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/cibundle' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/docker' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/header' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/preprocess' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/pretest' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/stats' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/test_bundle' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/test_export' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/test_image' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/test_syntax' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/common' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/compress_attributes' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/constants' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/container_commands' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/patch_minified' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/pull_css' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/pull_font_svg' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/shortcut_paths' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/update_version' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/util/watchified_bundle' {
  declare module.exports: any;
}

declare module 'plotly.js/tasks/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plotly.js/build/plotcss.js' {
  declare module.exports: $Exports<'plotly.js/build/plotcss'>;
}
declare module 'plotly.js/build/ploticon.js' {
  declare module.exports: $Exports<'plotly.js/build/ploticon'>;
}
declare module 'plotly.js/dist/plotly-basic.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-basic'>;
}
declare module 'plotly.js/dist/plotly-basic.min.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-basic.min'>;
}
declare module 'plotly.js/dist/plotly-cartesian.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-cartesian'>;
}
declare module 'plotly.js/dist/plotly-cartesian.min.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-cartesian.min'>;
}
declare module 'plotly.js/dist/plotly-geo-assets.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-geo-assets'>;
}
declare module 'plotly.js/dist/plotly-geo.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-geo'>;
}
declare module 'plotly.js/dist/plotly-geo.min.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-geo.min'>;
}
declare module 'plotly.js/dist/plotly-gl2d.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-gl2d'>;
}
declare module 'plotly.js/dist/plotly-gl2d.min.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-gl2d.min'>;
}
declare module 'plotly.js/dist/plotly-gl3d.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-gl3d'>;
}
declare module 'plotly.js/dist/plotly-gl3d.min.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-gl3d.min'>;
}
declare module 'plotly.js/dist/plotly-mapbox.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-mapbox'>;
}
declare module 'plotly.js/dist/plotly-mapbox.min.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-mapbox.min'>;
}
declare module 'plotly.js/dist/plotly-with-meta.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly-with-meta'>;
}
declare module 'plotly.js/dist/plotly.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly'>;
}
declare module 'plotly.js/dist/plotly.min.js' {
  declare module.exports: $Exports<'plotly.js/dist/plotly.min'>;
}
declare module 'plotly.js/lib/bar.js' {
  declare module.exports: $Exports<'plotly.js/lib/bar'>;
}
declare module 'plotly.js/lib/box.js' {
  declare module.exports: $Exports<'plotly.js/lib/box'>;
}
declare module 'plotly.js/lib/choropleth.js' {
  declare module.exports: $Exports<'plotly.js/lib/choropleth'>;
}
declare module 'plotly.js/lib/contour.js' {
  declare module.exports: $Exports<'plotly.js/lib/contour'>;
}
declare module 'plotly.js/lib/contourgl.js' {
  declare module.exports: $Exports<'plotly.js/lib/contourgl'>;
}
declare module 'plotly.js/lib/core.js' {
  declare module.exports: $Exports<'plotly.js/lib/core'>;
}
declare module 'plotly.js/lib/heatmap.js' {
  declare module.exports: $Exports<'plotly.js/lib/heatmap'>;
}
declare module 'plotly.js/lib/heatmapgl.js' {
  declare module.exports: $Exports<'plotly.js/lib/heatmapgl'>;
}
declare module 'plotly.js/lib/histogram.js' {
  declare module.exports: $Exports<'plotly.js/lib/histogram'>;
}
declare module 'plotly.js/lib/histogram2d.js' {
  declare module.exports: $Exports<'plotly.js/lib/histogram2d'>;
}
declare module 'plotly.js/lib/histogram2dcontour.js' {
  declare module.exports: $Exports<'plotly.js/lib/histogram2dcontour'>;
}
declare module 'plotly.js/lib/index-basic.js' {
  declare module.exports: $Exports<'plotly.js/lib/index-basic'>;
}
declare module 'plotly.js/lib/index-cartesian.js' {
  declare module.exports: $Exports<'plotly.js/lib/index-cartesian'>;
}
declare module 'plotly.js/lib/index-geo.js' {
  declare module.exports: $Exports<'plotly.js/lib/index-geo'>;
}
declare module 'plotly.js/lib/index-gl2d.js' {
  declare module.exports: $Exports<'plotly.js/lib/index-gl2d'>;
}
declare module 'plotly.js/lib/index-gl3d.js' {
  declare module.exports: $Exports<'plotly.js/lib/index-gl3d'>;
}
declare module 'plotly.js/lib/index-mapbox.js' {
  declare module.exports: $Exports<'plotly.js/lib/index-mapbox'>;
}
declare module 'plotly.js/lib/index.js' {
  declare module.exports: $Exports<'plotly.js/lib/index'>;
}
declare module 'plotly.js/lib/mesh3d.js' {
  declare module.exports: $Exports<'plotly.js/lib/mesh3d'>;
}
declare module 'plotly.js/lib/pie.js' {
  declare module.exports: $Exports<'plotly.js/lib/pie'>;
}
declare module 'plotly.js/lib/pointcloud.js' {
  declare module.exports: $Exports<'plotly.js/lib/pointcloud'>;
}
declare module 'plotly.js/lib/scatter.js' {
  declare module.exports: $Exports<'plotly.js/lib/scatter'>;
}
declare module 'plotly.js/lib/scatter3d.js' {
  declare module.exports: $Exports<'plotly.js/lib/scatter3d'>;
}
declare module 'plotly.js/lib/scattergeo.js' {
  declare module.exports: $Exports<'plotly.js/lib/scattergeo'>;
}
declare module 'plotly.js/lib/scattergl.js' {
  declare module.exports: $Exports<'plotly.js/lib/scattergl'>;
}
declare module 'plotly.js/lib/scattermapbox.js' {
  declare module.exports: $Exports<'plotly.js/lib/scattermapbox'>;
}
declare module 'plotly.js/lib/scatterternary.js' {
  declare module.exports: $Exports<'plotly.js/lib/scatterternary'>;
}
declare module 'plotly.js/lib/surface.js' {
  declare module.exports: $Exports<'plotly.js/lib/surface'>;
}
declare module 'plotly.js/src/assets/geo_assets.js' {
  declare module.exports: $Exports<'plotly.js/src/assets/geo_assets'>;
}
declare module 'plotly.js/src/components/annotations/annotation_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/annotation_defaults'>;
}
declare module 'plotly.js/src/components/annotations/arrow_paths.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/arrow_paths'>;
}
declare module 'plotly.js/src/components/annotations/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/attributes'>;
}
declare module 'plotly.js/src/components/annotations/calc_autorange.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/calc_autorange'>;
}
declare module 'plotly.js/src/components/annotations/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/defaults'>;
}
declare module 'plotly.js/src/components/annotations/draw_arrow_head.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/draw_arrow_head'>;
}
declare module 'plotly.js/src/components/annotations/draw.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/draw'>;
}
declare module 'plotly.js/src/components/annotations/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/annotations/index'>;
}
declare module 'plotly.js/src/components/color/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/color/attributes'>;
}
declare module 'plotly.js/src/components/color/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/color/index'>;
}
declare module 'plotly.js/src/components/colorbar/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorbar/attributes'>;
}
declare module 'plotly.js/src/components/colorbar/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorbar/defaults'>;
}
declare module 'plotly.js/src/components/colorbar/draw.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorbar/draw'>;
}
declare module 'plotly.js/src/components/colorbar/has_colorbar.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorbar/has_colorbar'>;
}
declare module 'plotly.js/src/components/colorbar/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorbar/index'>;
}
declare module 'plotly.js/src/components/colorscale/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/attributes'>;
}
declare module 'plotly.js/src/components/colorscale/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/calc'>;
}
declare module 'plotly.js/src/components/colorscale/color_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/color_attributes'>;
}
declare module 'plotly.js/src/components/colorscale/default_scale.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/default_scale'>;
}
declare module 'plotly.js/src/components/colorscale/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/defaults'>;
}
declare module 'plotly.js/src/components/colorscale/flip_scale.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/flip_scale'>;
}
declare module 'plotly.js/src/components/colorscale/get_scale.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/get_scale'>;
}
declare module 'plotly.js/src/components/colorscale/has_colorscale.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/has_colorscale'>;
}
declare module 'plotly.js/src/components/colorscale/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/index'>;
}
declare module 'plotly.js/src/components/colorscale/is_valid_scale_array.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/is_valid_scale_array'>;
}
declare module 'plotly.js/src/components/colorscale/is_valid_scale.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/is_valid_scale'>;
}
declare module 'plotly.js/src/components/colorscale/make_scale_function.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/make_scale_function'>;
}
declare module 'plotly.js/src/components/colorscale/scales.js' {
  declare module.exports: $Exports<'plotly.js/src/components/colorscale/scales'>;
}
declare module 'plotly.js/src/components/dragelement/align.js' {
  declare module.exports: $Exports<'plotly.js/src/components/dragelement/align'>;
}
declare module 'plotly.js/src/components/dragelement/cursor.js' {
  declare module.exports: $Exports<'plotly.js/src/components/dragelement/cursor'>;
}
declare module 'plotly.js/src/components/dragelement/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/dragelement/index'>;
}
declare module 'plotly.js/src/components/dragelement/unhover.js' {
  declare module.exports: $Exports<'plotly.js/src/components/dragelement/unhover'>;
}
declare module 'plotly.js/src/components/drawing/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/drawing/index'>;
}
declare module 'plotly.js/src/components/drawing/symbol_defs.js' {
  declare module.exports: $Exports<'plotly.js/src/components/drawing/symbol_defs'>;
}
declare module 'plotly.js/src/components/errorbars/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/errorbars/attributes'>;
}
declare module 'plotly.js/src/components/errorbars/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/components/errorbars/calc'>;
}
declare module 'plotly.js/src/components/errorbars/compute_error.js' {
  declare module.exports: $Exports<'plotly.js/src/components/errorbars/compute_error'>;
}
declare module 'plotly.js/src/components/errorbars/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/errorbars/defaults'>;
}
declare module 'plotly.js/src/components/errorbars/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/errorbars/index'>;
}
declare module 'plotly.js/src/components/errorbars/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/components/errorbars/plot'>;
}
declare module 'plotly.js/src/components/errorbars/style.js' {
  declare module.exports: $Exports<'plotly.js/src/components/errorbars/style'>;
}
declare module 'plotly.js/src/components/images/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/images/attributes'>;
}
declare module 'plotly.js/src/components/images/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/images/defaults'>;
}
declare module 'plotly.js/src/components/images/draw.js' {
  declare module.exports: $Exports<'plotly.js/src/components/images/draw'>;
}
declare module 'plotly.js/src/components/images/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/images/index'>;
}
declare module 'plotly.js/src/components/legend/anchor_utils.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/anchor_utils'>;
}
declare module 'plotly.js/src/components/legend/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/attributes'>;
}
declare module 'plotly.js/src/components/legend/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/constants'>;
}
declare module 'plotly.js/src/components/legend/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/defaults'>;
}
declare module 'plotly.js/src/components/legend/draw.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/draw'>;
}
declare module 'plotly.js/src/components/legend/get_legend_data.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/get_legend_data'>;
}
declare module 'plotly.js/src/components/legend/helpers.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/helpers'>;
}
declare module 'plotly.js/src/components/legend/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/index'>;
}
declare module 'plotly.js/src/components/legend/style.js' {
  declare module.exports: $Exports<'plotly.js/src/components/legend/style'>;
}
declare module 'plotly.js/src/components/modebar/buttons.js' {
  declare module.exports: $Exports<'plotly.js/src/components/modebar/buttons'>;
}
declare module 'plotly.js/src/components/modebar/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/modebar/index'>;
}
declare module 'plotly.js/src/components/modebar/manage.js' {
  declare module.exports: $Exports<'plotly.js/src/components/modebar/manage'>;
}
declare module 'plotly.js/src/components/modebar/modebar.js' {
  declare module.exports: $Exports<'plotly.js/src/components/modebar/modebar'>;
}
declare module 'plotly.js/src/components/rangeselector/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeselector/attributes'>;
}
declare module 'plotly.js/src/components/rangeselector/button_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeselector/button_attributes'>;
}
declare module 'plotly.js/src/components/rangeselector/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeselector/constants'>;
}
declare module 'plotly.js/src/components/rangeselector/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeselector/defaults'>;
}
declare module 'plotly.js/src/components/rangeselector/draw.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeselector/draw'>;
}
declare module 'plotly.js/src/components/rangeselector/get_update_object.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeselector/get_update_object'>;
}
declare module 'plotly.js/src/components/rangeselector/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeselector/index'>;
}
declare module 'plotly.js/src/components/rangeslider/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeslider/attributes'>;
}
declare module 'plotly.js/src/components/rangeslider/create_slider.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeslider/create_slider'>;
}
declare module 'plotly.js/src/components/rangeslider/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeslider/defaults'>;
}
declare module 'plotly.js/src/components/rangeslider/helpers.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeslider/helpers'>;
}
declare module 'plotly.js/src/components/rangeslider/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeslider/index'>;
}
declare module 'plotly.js/src/components/rangeslider/range_plot.js' {
  declare module.exports: $Exports<'plotly.js/src/components/rangeslider/range_plot'>;
}
declare module 'plotly.js/src/components/shapes/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/attributes'>;
}
declare module 'plotly.js/src/components/shapes/calc_autorange.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/calc_autorange'>;
}
declare module 'plotly.js/src/components/shapes/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/constants'>;
}
declare module 'plotly.js/src/components/shapes/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/defaults'>;
}
declare module 'plotly.js/src/components/shapes/draw.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/draw'>;
}
declare module 'plotly.js/src/components/shapes/helpers.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/helpers'>;
}
declare module 'plotly.js/src/components/shapes/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/index'>;
}
declare module 'plotly.js/src/components/shapes/shape_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/shapes/shape_defaults'>;
}
declare module 'plotly.js/src/components/titles/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/titles/index'>;
}
declare module 'plotly.js/src/components/updatemenus/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/components/updatemenus/attributes'>;
}
declare module 'plotly.js/src/components/updatemenus/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/components/updatemenus/constants'>;
}
declare module 'plotly.js/src/components/updatemenus/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/components/updatemenus/defaults'>;
}
declare module 'plotly.js/src/components/updatemenus/draw.js' {
  declare module.exports: $Exports<'plotly.js/src/components/updatemenus/draw'>;
}
declare module 'plotly.js/src/components/updatemenus/index.js' {
  declare module.exports: $Exports<'plotly.js/src/components/updatemenus/index'>;
}
declare module 'plotly.js/src/constants/gl_markers.js' {
  declare module.exports: $Exports<'plotly.js/src/constants/gl_markers'>;
}
declare module 'plotly.js/src/constants/gl2d_dashes.js' {
  declare module.exports: $Exports<'plotly.js/src/constants/gl2d_dashes'>;
}
declare module 'plotly.js/src/constants/gl3d_dashes.js' {
  declare module.exports: $Exports<'plotly.js/src/constants/gl3d_dashes'>;
}
declare module 'plotly.js/src/constants/string_mappings.js' {
  declare module.exports: $Exports<'plotly.js/src/constants/string_mappings'>;
}
declare module 'plotly.js/src/constants/xmlns_namespaces.js' {
  declare module.exports: $Exports<'plotly.js/src/constants/xmlns_namespaces'>;
}
declare module 'plotly.js/src/core.js' {
  declare module.exports: $Exports<'plotly.js/src/core'>;
}
declare module 'plotly.js/src/fonts/mathjax_config.js' {
  declare module.exports: $Exports<'plotly.js/src/fonts/mathjax_config'>;
}
declare module 'plotly.js/src/lib/array_to_calc_item.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/array_to_calc_item'>;
}
declare module 'plotly.js/src/lib/coerce.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/coerce'>;
}
declare module 'plotly.js/src/lib/dates.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/dates'>;
}
declare module 'plotly.js/src/lib/events.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/events'>;
}
declare module 'plotly.js/src/lib/extend.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/extend'>;
}
declare module 'plotly.js/src/lib/filter_visible.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/filter_visible'>;
}
declare module 'plotly.js/src/lib/float32_truncate.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/float32_truncate'>;
}
declare module 'plotly.js/src/lib/geo_location_utils.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/geo_location_utils'>;
}
declare module 'plotly.js/src/lib/gl_format_color.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/gl_format_color'>;
}
declare module 'plotly.js/src/lib/html2unicode.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/html2unicode'>;
}
declare module 'plotly.js/src/lib/index.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/index'>;
}
declare module 'plotly.js/src/lib/is_array.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/is_array'>;
}
declare module 'plotly.js/src/lib/is_plain_object.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/is_plain_object'>;
}
declare module 'plotly.js/src/lib/loggers.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/loggers'>;
}
declare module 'plotly.js/src/lib/matrix.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/matrix'>;
}
declare module 'plotly.js/src/lib/nested_property.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/nested_property'>;
}
declare module 'plotly.js/src/lib/notifier.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/notifier'>;
}
declare module 'plotly.js/src/lib/polygon.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/polygon'>;
}
declare module 'plotly.js/src/lib/queue.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/queue'>;
}
declare module 'plotly.js/src/lib/search.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/search'>;
}
declare module 'plotly.js/src/lib/setcursor.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/setcursor'>;
}
declare module 'plotly.js/src/lib/show_no_webgl_msg.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/show_no_webgl_msg'>;
}
declare module 'plotly.js/src/lib/stats.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/stats'>;
}
declare module 'plotly.js/src/lib/str2rgbarray.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/str2rgbarray'>;
}
declare module 'plotly.js/src/lib/svg_text_utils.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/svg_text_utils'>;
}
declare module 'plotly.js/src/lib/topojson_utils.js' {
  declare module.exports: $Exports<'plotly.js/src/lib/topojson_utils'>;
}
declare module 'plotly.js/src/plot_api/helpers.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/helpers'>;
}
declare module 'plotly.js/src/plot_api/plot_api.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/plot_api'>;
}
declare module 'plotly.js/src/plot_api/plot_config.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/plot_config'>;
}
declare module 'plotly.js/src/plot_api/plot_schema.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/plot_schema'>;
}
declare module 'plotly.js/src/plot_api/register.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/register'>;
}
declare module 'plotly.js/src/plot_api/set_plot_config.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/set_plot_config'>;
}
declare module 'plotly.js/src/plot_api/subroutines.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/subroutines'>;
}
declare module 'plotly.js/src/plot_api/to_image.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/to_image'>;
}
declare module 'plotly.js/src/plot_api/validate.js' {
  declare module.exports: $Exports<'plotly.js/src/plot_api/validate'>;
}
declare module 'plotly.js/src/plotly.js' {
  declare module.exports: $Exports<'plotly.js/src/plotly'>;
}
declare module 'plotly.js/src/plots/animation_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/animation_attributes'>;
}
declare module 'plotly.js/src/plots/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/attributes'>;
}
declare module 'plotly.js/src/plots/cartesian/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/attributes'>;
}
declare module 'plotly.js/src/plots/cartesian/axes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/axes'>;
}
declare module 'plotly.js/src/plots/cartesian/axis_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/axis_defaults'>;
}
declare module 'plotly.js/src/plots/cartesian/axis_ids.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/axis_ids'>;
}
declare module 'plotly.js/src/plots/cartesian/category_order_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/category_order_defaults'>;
}
declare module 'plotly.js/src/plots/cartesian/clean_datum.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/clean_datum'>;
}
declare module 'plotly.js/src/plots/cartesian/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/constants'>;
}
declare module 'plotly.js/src/plots/cartesian/dragbox.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/dragbox'>;
}
declare module 'plotly.js/src/plots/cartesian/graph_interact.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/graph_interact'>;
}
declare module 'plotly.js/src/plots/cartesian/index.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/index'>;
}
declare module 'plotly.js/src/plots/cartesian/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/layout_attributes'>;
}
declare module 'plotly.js/src/plots/cartesian/layout_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/layout_defaults'>;
}
declare module 'plotly.js/src/plots/cartesian/ordered_categories.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/ordered_categories'>;
}
declare module 'plotly.js/src/plots/cartesian/position_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/position_defaults'>;
}
declare module 'plotly.js/src/plots/cartesian/select.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/select'>;
}
declare module 'plotly.js/src/plots/cartesian/set_convert.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/set_convert'>;
}
declare module 'plotly.js/src/plots/cartesian/tick_label_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/tick_label_defaults'>;
}
declare module 'plotly.js/src/plots/cartesian/tick_mark_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/tick_mark_defaults'>;
}
declare module 'plotly.js/src/plots/cartesian/tick_value_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/tick_value_defaults'>;
}
declare module 'plotly.js/src/plots/cartesian/transition_axes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/cartesian/transition_axes'>;
}
declare module 'plotly.js/src/plots/font_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/font_attributes'>;
}
declare module 'plotly.js/src/plots/frame_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/frame_attributes'>;
}
declare module 'plotly.js/src/plots/geo/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/constants'>;
}
declare module 'plotly.js/src/plots/geo/geo.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/geo'>;
}
declare module 'plotly.js/src/plots/geo/index.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/index'>;
}
declare module 'plotly.js/src/plots/geo/layout/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/layout/attributes'>;
}
declare module 'plotly.js/src/plots/geo/layout/axis_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/layout/axis_attributes'>;
}
declare module 'plotly.js/src/plots/geo/layout/axis_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/layout/axis_defaults'>;
}
declare module 'plotly.js/src/plots/geo/layout/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/layout/defaults'>;
}
declare module 'plotly.js/src/plots/geo/layout/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/layout/layout_attributes'>;
}
declare module 'plotly.js/src/plots/geo/projections.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/projections'>;
}
declare module 'plotly.js/src/plots/geo/set_scale.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/set_scale'>;
}
declare module 'plotly.js/src/plots/geo/zoom_reset.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/zoom_reset'>;
}
declare module 'plotly.js/src/plots/geo/zoom.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/geo/zoom'>;
}
declare module 'plotly.js/src/plots/gl2d/camera.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl2d/camera'>;
}
declare module 'plotly.js/src/plots/gl2d/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl2d/convert'>;
}
declare module 'plotly.js/src/plots/gl2d/index.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl2d/index'>;
}
declare module 'plotly.js/src/plots/gl2d/scene2d.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl2d/scene2d'>;
}
declare module 'plotly.js/src/plots/gl3d/camera.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/camera'>;
}
declare module 'plotly.js/src/plots/gl3d/index.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/index'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/attributes'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/axis_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/axis_attributes'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/axis_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/axis_defaults'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/convert'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/defaults'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/layout_attributes'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/spikes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/spikes'>;
}
declare module 'plotly.js/src/plots/gl3d/layout/tick_marks.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/layout/tick_marks'>;
}
declare module 'plotly.js/src/plots/gl3d/project.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/project'>;
}
declare module 'plotly.js/src/plots/gl3d/scene.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/scene'>;
}
declare module 'plotly.js/src/plots/gl3d/set_convert.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/gl3d/set_convert'>;
}
declare module 'plotly.js/src/plots/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/layout_attributes'>;
}
declare module 'plotly.js/src/plots/mapbox/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/mapbox/constants'>;
}
declare module 'plotly.js/src/plots/mapbox/convert_text_opts.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/mapbox/convert_text_opts'>;
}
declare module 'plotly.js/src/plots/mapbox/index.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/mapbox/index'>;
}
declare module 'plotly.js/src/plots/mapbox/layers.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/mapbox/layers'>;
}
declare module 'plotly.js/src/plots/mapbox/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/mapbox/layout_attributes'>;
}
declare module 'plotly.js/src/plots/mapbox/layout_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/mapbox/layout_defaults'>;
}
declare module 'plotly.js/src/plots/mapbox/mapbox.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/mapbox/mapbox'>;
}
declare module 'plotly.js/src/plots/plots.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/plots'>;
}
declare module 'plotly.js/src/plots/polar/area_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/polar/area_attributes'>;
}
declare module 'plotly.js/src/plots/polar/axis_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/polar/axis_attributes'>;
}
declare module 'plotly.js/src/plots/polar/index.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/polar/index'>;
}
declare module 'plotly.js/src/plots/polar/micropolar_manager.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/polar/micropolar_manager'>;
}
declare module 'plotly.js/src/plots/polar/micropolar.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/polar/micropolar'>;
}
declare module 'plotly.js/src/plots/polar/undo_manager.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/polar/undo_manager'>;
}
declare module 'plotly.js/src/plots/subplot_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/subplot_defaults'>;
}
declare module 'plotly.js/src/plots/ternary/index.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/ternary/index'>;
}
declare module 'plotly.js/src/plots/ternary/layout/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/ternary/layout/attributes'>;
}
declare module 'plotly.js/src/plots/ternary/layout/axis_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/ternary/layout/axis_attributes'>;
}
declare module 'plotly.js/src/plots/ternary/layout/axis_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/ternary/layout/axis_defaults'>;
}
declare module 'plotly.js/src/plots/ternary/layout/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/ternary/layout/defaults'>;
}
declare module 'plotly.js/src/plots/ternary/layout/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/ternary/layout/layout_attributes'>;
}
declare module 'plotly.js/src/plots/ternary/ternary.js' {
  declare module.exports: $Exports<'plotly.js/src/plots/ternary/ternary'>;
}
declare module 'plotly.js/src/registry.js' {
  declare module.exports: $Exports<'plotly.js/src/registry'>;
}
declare module 'plotly.js/src/snapshot/cloneplot.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/cloneplot'>;
}
declare module 'plotly.js/src/snapshot/download.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/download'>;
}
declare module 'plotly.js/src/snapshot/filesaver.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/filesaver'>;
}
declare module 'plotly.js/src/snapshot/helpers.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/helpers'>;
}
declare module 'plotly.js/src/snapshot/index.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/index'>;
}
declare module 'plotly.js/src/snapshot/svgtoimg.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/svgtoimg'>;
}
declare module 'plotly.js/src/snapshot/toimage.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/toimage'>;
}
declare module 'plotly.js/src/snapshot/tosvg.js' {
  declare module.exports: $Exports<'plotly.js/src/snapshot/tosvg'>;
}
declare module 'plotly.js/src/traces/bar/arrays_to_calcdata.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/arrays_to_calcdata'>;
}
declare module 'plotly.js/src/traces/bar/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/attributes'>;
}
declare module 'plotly.js/src/traces/bar/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/calc'>;
}
declare module 'plotly.js/src/traces/bar/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/defaults'>;
}
declare module 'plotly.js/src/traces/bar/hover.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/hover'>;
}
declare module 'plotly.js/src/traces/bar/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/index'>;
}
declare module 'plotly.js/src/traces/bar/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/layout_attributes'>;
}
declare module 'plotly.js/src/traces/bar/layout_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/layout_defaults'>;
}
declare module 'plotly.js/src/traces/bar/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/plot'>;
}
declare module 'plotly.js/src/traces/bar/set_positions.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/set_positions'>;
}
declare module 'plotly.js/src/traces/bar/style_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/style_defaults'>;
}
declare module 'plotly.js/src/traces/bar/style.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/bar/style'>;
}
declare module 'plotly.js/src/traces/box/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/attributes'>;
}
declare module 'plotly.js/src/traces/box/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/calc'>;
}
declare module 'plotly.js/src/traces/box/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/defaults'>;
}
declare module 'plotly.js/src/traces/box/hover.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/hover'>;
}
declare module 'plotly.js/src/traces/box/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/index'>;
}
declare module 'plotly.js/src/traces/box/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/layout_attributes'>;
}
declare module 'plotly.js/src/traces/box/layout_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/layout_defaults'>;
}
declare module 'plotly.js/src/traces/box/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/plot'>;
}
declare module 'plotly.js/src/traces/box/set_positions.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/set_positions'>;
}
declare module 'plotly.js/src/traces/box/style.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/box/style'>;
}
declare module 'plotly.js/src/traces/choropleth/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/choropleth/attributes'>;
}
declare module 'plotly.js/src/traces/choropleth/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/choropleth/calc'>;
}
declare module 'plotly.js/src/traces/choropleth/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/choropleth/defaults'>;
}
declare module 'plotly.js/src/traces/choropleth/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/choropleth/index'>;
}
declare module 'plotly.js/src/traces/choropleth/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/choropleth/plot'>;
}
declare module 'plotly.js/src/traces/contour/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/attributes'>;
}
declare module 'plotly.js/src/traces/contour/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/calc'>;
}
declare module 'plotly.js/src/traces/contour/colorbar.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/colorbar'>;
}
declare module 'plotly.js/src/traces/contour/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/defaults'>;
}
declare module 'plotly.js/src/traces/contour/hover.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/hover'>;
}
declare module 'plotly.js/src/traces/contour/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/index'>;
}
declare module 'plotly.js/src/traces/contour/make_color_map.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/make_color_map'>;
}
declare module 'plotly.js/src/traces/contour/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/plot'>;
}
declare module 'plotly.js/src/traces/contour/style_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/style_defaults'>;
}
declare module 'plotly.js/src/traces/contour/style.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contour/style'>;
}
declare module 'plotly.js/src/traces/contourgl/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contourgl/convert'>;
}
declare module 'plotly.js/src/traces/contourgl/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/contourgl/index'>;
}
declare module 'plotly.js/src/traces/heatmap/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/attributes'>;
}
declare module 'plotly.js/src/traces/heatmap/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/calc'>;
}
declare module 'plotly.js/src/traces/heatmap/colorbar.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/colorbar'>;
}
declare module 'plotly.js/src/traces/heatmap/convert_column_xyz.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/convert_column_xyz'>;
}
declare module 'plotly.js/src/traces/heatmap/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/defaults'>;
}
declare module 'plotly.js/src/traces/heatmap/has_columns.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/has_columns'>;
}
declare module 'plotly.js/src/traces/heatmap/hover.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/hover'>;
}
declare module 'plotly.js/src/traces/heatmap/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/index'>;
}
declare module 'plotly.js/src/traces/heatmap/max_row_length.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/max_row_length'>;
}
declare module 'plotly.js/src/traces/heatmap/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/plot'>;
}
declare module 'plotly.js/src/traces/heatmap/style.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/style'>;
}
declare module 'plotly.js/src/traces/heatmap/xyz_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmap/xyz_defaults'>;
}
declare module 'plotly.js/src/traces/heatmapgl/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmapgl/attributes'>;
}
declare module 'plotly.js/src/traces/heatmapgl/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmapgl/convert'>;
}
declare module 'plotly.js/src/traces/heatmapgl/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/heatmapgl/index'>;
}
declare module 'plotly.js/src/traces/histogram/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/attributes'>;
}
declare module 'plotly.js/src/traces/histogram/average.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/average'>;
}
declare module 'plotly.js/src/traces/histogram/bin_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/bin_defaults'>;
}
declare module 'plotly.js/src/traces/histogram/bin_functions.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/bin_functions'>;
}
declare module 'plotly.js/src/traces/histogram/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/calc'>;
}
declare module 'plotly.js/src/traces/histogram/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/defaults'>;
}
declare module 'plotly.js/src/traces/histogram/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/index'>;
}
declare module 'plotly.js/src/traces/histogram/norm_functions.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram/norm_functions'>;
}
declare module 'plotly.js/src/traces/histogram2d/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2d/attributes'>;
}
declare module 'plotly.js/src/traces/histogram2d/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2d/calc'>;
}
declare module 'plotly.js/src/traces/histogram2d/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2d/defaults'>;
}
declare module 'plotly.js/src/traces/histogram2d/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2d/index'>;
}
declare module 'plotly.js/src/traces/histogram2d/sample_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2d/sample_defaults'>;
}
declare module 'plotly.js/src/traces/histogram2dcontour/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2dcontour/attributes'>;
}
declare module 'plotly.js/src/traces/histogram2dcontour/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2dcontour/defaults'>;
}
declare module 'plotly.js/src/traces/histogram2dcontour/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/histogram2dcontour/index'>;
}
declare module 'plotly.js/src/traces/mesh3d/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/mesh3d/attributes'>;
}
declare module 'plotly.js/src/traces/mesh3d/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/mesh3d/convert'>;
}
declare module 'plotly.js/src/traces/mesh3d/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/mesh3d/defaults'>;
}
declare module 'plotly.js/src/traces/mesh3d/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/mesh3d/index'>;
}
declare module 'plotly.js/src/traces/pie/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/attributes'>;
}
declare module 'plotly.js/src/traces/pie/base_plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/base_plot'>;
}
declare module 'plotly.js/src/traces/pie/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/calc'>;
}
declare module 'plotly.js/src/traces/pie/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/defaults'>;
}
declare module 'plotly.js/src/traces/pie/helpers.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/helpers'>;
}
declare module 'plotly.js/src/traces/pie/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/index'>;
}
declare module 'plotly.js/src/traces/pie/layout_attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/layout_attributes'>;
}
declare module 'plotly.js/src/traces/pie/layout_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/layout_defaults'>;
}
declare module 'plotly.js/src/traces/pie/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/plot'>;
}
declare module 'plotly.js/src/traces/pie/style_one.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/style_one'>;
}
declare module 'plotly.js/src/traces/pie/style.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pie/style'>;
}
declare module 'plotly.js/src/traces/pointcloud/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pointcloud/attributes'>;
}
declare module 'plotly.js/src/traces/pointcloud/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pointcloud/convert'>;
}
declare module 'plotly.js/src/traces/pointcloud/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pointcloud/defaults'>;
}
declare module 'plotly.js/src/traces/pointcloud/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/pointcloud/index'>;
}
declare module 'plotly.js/src/traces/scatter/arrays_to_calcdata.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/arrays_to_calcdata'>;
}
declare module 'plotly.js/src/traces/scatter/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/attributes'>;
}
declare module 'plotly.js/src/traces/scatter/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/calc'>;
}
declare module 'plotly.js/src/traces/scatter/clean_data.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/clean_data'>;
}
declare module 'plotly.js/src/traces/scatter/colorbar.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/colorbar'>;
}
declare module 'plotly.js/src/traces/scatter/colorscale_calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/colorscale_calc'>;
}
declare module 'plotly.js/src/traces/scatter/constants.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/constants'>;
}
declare module 'plotly.js/src/traces/scatter/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/defaults'>;
}
declare module 'plotly.js/src/traces/scatter/fillcolor_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/fillcolor_defaults'>;
}
declare module 'plotly.js/src/traces/scatter/get_trace_color.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/get_trace_color'>;
}
declare module 'plotly.js/src/traces/scatter/hover.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/hover'>;
}
declare module 'plotly.js/src/traces/scatter/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/index'>;
}
declare module 'plotly.js/src/traces/scatter/line_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/line_defaults'>;
}
declare module 'plotly.js/src/traces/scatter/line_points.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/line_points'>;
}
declare module 'plotly.js/src/traces/scatter/line_shape_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/line_shape_defaults'>;
}
declare module 'plotly.js/src/traces/scatter/link_traces.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/link_traces'>;
}
declare module 'plotly.js/src/traces/scatter/make_bubble_size_func.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/make_bubble_size_func'>;
}
declare module 'plotly.js/src/traces/scatter/marker_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/marker_defaults'>;
}
declare module 'plotly.js/src/traces/scatter/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/plot'>;
}
declare module 'plotly.js/src/traces/scatter/select.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/select'>;
}
declare module 'plotly.js/src/traces/scatter/style.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/style'>;
}
declare module 'plotly.js/src/traces/scatter/subtypes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/subtypes'>;
}
declare module 'plotly.js/src/traces/scatter/text_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/text_defaults'>;
}
declare module 'plotly.js/src/traces/scatter/xy_defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter/xy_defaults'>;
}
declare module 'plotly.js/src/traces/scatter3d/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter3d/attributes'>;
}
declare module 'plotly.js/src/traces/scatter3d/calc_errors.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter3d/calc_errors'>;
}
declare module 'plotly.js/src/traces/scatter3d/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter3d/calc'>;
}
declare module 'plotly.js/src/traces/scatter3d/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter3d/convert'>;
}
declare module 'plotly.js/src/traces/scatter3d/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter3d/defaults'>;
}
declare module 'plotly.js/src/traces/scatter3d/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatter3d/index'>;
}
declare module 'plotly.js/src/traces/scattergeo/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergeo/attributes'>;
}
declare module 'plotly.js/src/traces/scattergeo/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergeo/calc'>;
}
declare module 'plotly.js/src/traces/scattergeo/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergeo/defaults'>;
}
declare module 'plotly.js/src/traces/scattergeo/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergeo/index'>;
}
declare module 'plotly.js/src/traces/scattergeo/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergeo/plot'>;
}
declare module 'plotly.js/src/traces/scattergl/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergl/attributes'>;
}
declare module 'plotly.js/src/traces/scattergl/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergl/convert'>;
}
declare module 'plotly.js/src/traces/scattergl/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergl/defaults'>;
}
declare module 'plotly.js/src/traces/scattergl/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattergl/index'>;
}
declare module 'plotly.js/src/traces/scattermapbox/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattermapbox/attributes'>;
}
declare module 'plotly.js/src/traces/scattermapbox/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattermapbox/calc'>;
}
declare module 'plotly.js/src/traces/scattermapbox/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattermapbox/convert'>;
}
declare module 'plotly.js/src/traces/scattermapbox/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattermapbox/defaults'>;
}
declare module 'plotly.js/src/traces/scattermapbox/hover.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattermapbox/hover'>;
}
declare module 'plotly.js/src/traces/scattermapbox/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattermapbox/index'>;
}
declare module 'plotly.js/src/traces/scattermapbox/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scattermapbox/plot'>;
}
declare module 'plotly.js/src/traces/scatterternary/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/attributes'>;
}
declare module 'plotly.js/src/traces/scatterternary/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/calc'>;
}
declare module 'plotly.js/src/traces/scatterternary/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/defaults'>;
}
declare module 'plotly.js/src/traces/scatterternary/hover.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/hover'>;
}
declare module 'plotly.js/src/traces/scatterternary/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/index'>;
}
declare module 'plotly.js/src/traces/scatterternary/plot.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/plot'>;
}
declare module 'plotly.js/src/traces/scatterternary/select.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/select'>;
}
declare module 'plotly.js/src/traces/scatterternary/style.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/scatterternary/style'>;
}
declare module 'plotly.js/src/traces/surface/attributes.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/surface/attributes'>;
}
declare module 'plotly.js/src/traces/surface/calc.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/surface/calc'>;
}
declare module 'plotly.js/src/traces/surface/colorbar.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/surface/colorbar'>;
}
declare module 'plotly.js/src/traces/surface/convert.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/surface/convert'>;
}
declare module 'plotly.js/src/traces/surface/defaults.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/surface/defaults'>;
}
declare module 'plotly.js/src/traces/surface/index.js' {
  declare module.exports: $Exports<'plotly.js/src/traces/surface/index'>;
}
declare module 'plotly.js/tasks/baseline.js' {
  declare module.exports: $Exports<'plotly.js/tasks/baseline'>;
}
declare module 'plotly.js/tasks/bundle.js' {
  declare module.exports: $Exports<'plotly.js/tasks/bundle'>;
}
declare module 'plotly.js/tasks/cibundle.js' {
  declare module.exports: $Exports<'plotly.js/tasks/cibundle'>;
}
declare module 'plotly.js/tasks/docker.js' {
  declare module.exports: $Exports<'plotly.js/tasks/docker'>;
}
declare module 'plotly.js/tasks/header.js' {
  declare module.exports: $Exports<'plotly.js/tasks/header'>;
}
declare module 'plotly.js/tasks/preprocess.js' {
  declare module.exports: $Exports<'plotly.js/tasks/preprocess'>;
}
declare module 'plotly.js/tasks/pretest.js' {
  declare module.exports: $Exports<'plotly.js/tasks/pretest'>;
}
declare module 'plotly.js/tasks/stats.js' {
  declare module.exports: $Exports<'plotly.js/tasks/stats'>;
}
declare module 'plotly.js/tasks/test_bundle.js' {
  declare module.exports: $Exports<'plotly.js/tasks/test_bundle'>;
}
declare module 'plotly.js/tasks/test_export.js' {
  declare module.exports: $Exports<'plotly.js/tasks/test_export'>;
}
declare module 'plotly.js/tasks/test_image.js' {
  declare module.exports: $Exports<'plotly.js/tasks/test_image'>;
}
declare module 'plotly.js/tasks/test_syntax.js' {
  declare module.exports: $Exports<'plotly.js/tasks/test_syntax'>;
}
declare module 'plotly.js/tasks/util/common.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/common'>;
}
declare module 'plotly.js/tasks/util/compress_attributes.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/compress_attributes'>;
}
declare module 'plotly.js/tasks/util/constants.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/constants'>;
}
declare module 'plotly.js/tasks/util/container_commands.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/container_commands'>;
}
declare module 'plotly.js/tasks/util/patch_minified.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/patch_minified'>;
}
declare module 'plotly.js/tasks/util/pull_css.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/pull_css'>;
}
declare module 'plotly.js/tasks/util/pull_font_svg.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/pull_font_svg'>;
}
declare module 'plotly.js/tasks/util/shortcut_paths.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/shortcut_paths'>;
}
declare module 'plotly.js/tasks/util/update_version.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/update_version'>;
}
declare module 'plotly.js/tasks/util/watchified_bundle.js' {
  declare module.exports: $Exports<'plotly.js/tasks/util/watchified_bundle'>;
}
declare module 'plotly.js/tasks/watch.js' {
  declare module.exports: $Exports<'plotly.js/tasks/watch'>;
}
