// flow-typed signature: 21eed19ff997d9bd95e219dbe1f91dca
// flow-typed version: <<STUB>>/react-simple-dropdown_v^1.1.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-simple-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-simple-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-simple-dropdown/components/Dropdown' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/components/DropdownContent' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/components/DropdownTrigger' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/lib/components/Dropdown' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/lib/components/DropdownContent' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/lib/components/DropdownTrigger' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/test/components/Dropdown' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/test/components/DropdownContent' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/test/components/DropdownTrigger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-simple-dropdown/components/Dropdown.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/components/Dropdown'>;
}
declare module 'react-simple-dropdown/components/DropdownContent.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/components/DropdownContent'>;
}
declare module 'react-simple-dropdown/components/DropdownTrigger.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/components/DropdownTrigger'>;
}
declare module 'react-simple-dropdown/lib/components/Dropdown.js' {
  declare module.exports: $Exports<'react-simple-dropdown/lib/components/Dropdown'>;
}
declare module 'react-simple-dropdown/lib/components/DropdownContent.js' {
  declare module.exports: $Exports<'react-simple-dropdown/lib/components/DropdownContent'>;
}
declare module 'react-simple-dropdown/lib/components/DropdownTrigger.js' {
  declare module.exports: $Exports<'react-simple-dropdown/lib/components/DropdownTrigger'>;
}
declare module 'react-simple-dropdown/test/components/Dropdown.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/test/components/Dropdown'>;
}
declare module 'react-simple-dropdown/test/components/DropdownContent.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/test/components/DropdownContent'>;
}
declare module 'react-simple-dropdown/test/components/DropdownTrigger.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/test/components/DropdownTrigger'>;
}
