// flow-typed signature: 5ec4b9b7dc8952a6368be25b3d697c3e
// flow-typed version: <<STUB>>/uuid_v^2.0.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid/benchmark/benchmark' {
  declare module.exports: any;
}

declare module 'uuid/misc/compare' {
  declare module.exports: any;
}

declare module 'uuid/misc/perf' {
  declare module.exports: any;
}

declare module 'uuid/rng-browser' {
  declare module.exports: any;
}

declare module 'uuid/rng' {
  declare module.exports: any;
}

declare module 'uuid/test/test' {
  declare module.exports: any;
}

declare module 'uuid/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid/benchmark/benchmark.js' {
  declare module.exports: $Exports<'uuid/benchmark/benchmark'>;
}
declare module 'uuid/misc/compare.js' {
  declare module.exports: $Exports<'uuid/misc/compare'>;
}
declare module 'uuid/misc/perf.js' {
  declare module.exports: $Exports<'uuid/misc/perf'>;
}
declare module 'uuid/rng-browser.js' {
  declare module.exports: $Exports<'uuid/rng-browser'>;
}
declare module 'uuid/rng.js' {
  declare module.exports: $Exports<'uuid/rng'>;
}
declare module 'uuid/test/test.js' {
  declare module.exports: $Exports<'uuid/test/test'>;
}
declare module 'uuid/uuid.js' {
  declare module.exports: $Exports<'uuid/uuid'>;
}
